# application: modular-security-system
# version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /api/(.*)
  script: main.app

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

env_variables:
  BUCKET_NAME: modular-security-system
  PUBSUB_URL: https://pubsub-dot-modular-security-system.appspot.com/pubsub/datareceived
