# application: modular-security-system
# version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: ssl
  version: latest

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /api/(.*)
  script: main.app

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)

env_variables:
  BUCKET_NAME: modular-security-system
  PUBSUB_URL: https://pubsub-dot-modular-security-system.appspot.com/pubsub/datareceived?token=1234abc
  SENTRY_DSN: https://8c56117152634659884a65d282a48dea:70c7004fed644254a1f4ab367556d473@sentry.io/192183
